# Generated by Django 4.0.5 on 2022-06-10 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Date_of_Birth',
            field=models.DateField(default=datetime.datetime(2022, 6, 10, 18, 21, 15, 767909)),
        ),
    ]
