# Generated by Django 4.0.5 on 2022-06-15 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Date_of_Birth',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 17, 21, 40, 919954)),
        ),
    ]
