# Generated by Django 4.0.4 on 2022-06-27 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Date_of_Birth',
            field=models.DateField(default=datetime.datetime(2022, 6, 27, 18, 15, 56, 535625)),
        ),
    ]
