# Generated by Django 4.0.4 on 2022-06-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_rating_guest_alter_reservation_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorlist',
            name='freetime',
        ),
        migrations.AddField(
            model_name='doctorlist',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
