# Generated by Django 4.0.4 on 2022-06-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_doctorlist_freetime_doctorlist_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.CharField(choices=[('30mins', 'halfhour'), ('60mins', 'onehour'), ('90mins', 'hourandhalf')], max_length=10),
        ),
    ]
